defaults:
  default-role: developer
  merge: true
  model: "openai/gpt-5.3-codex"
  max-tool-threads: 4
  max-threads: 4
  log-llm-requests: true
  thinking: medium
  lsp-server: /home/rlew/go/bin/gopls
  allow-all-permissions: true
  worktree: csw-%
  vfs-allow:
    - "/home/rlew/codesnort/src/csw/_local/files"
  container:
    image: "golang:1.25-trixie"
    enabled: true
