package presenter

import (
	"sync"

	"github.com/codesnort/codesnort-swe/pkg/core"
	"github.com/codesnort/codesnort-swe/pkg/models"
	"github.com/codesnort/codesnort-swe/pkg/tool"
	"github.com/codesnort/codesnort-swe/pkg/ui"
)

// ChatPresenter implements ui.ChatPresenter and core.SessionThreadOutput.
// It acts as a bridge between the SessionThread and the ChatView,
// translating session events into UI updates.
type ChatPresenter struct {
	mu     sync.Mutex
	view   ui.ChatView
	thread *core.SessionThread
	system *core.SweSystem

	// Tracking state for streaming
	currentAssistantMessage *ui.ChatMessageUI
	messageCounter          int
	toolCallCounter         int
}

// NewChatPresenter creates a new ChatPresenter with the given system and session thread.
func NewChatPresenter(system *core.SweSystem, thread *core.SessionThread) *ChatPresenter {
	p := &ChatPresenter{
		system: system,
		thread: thread,
	}
	// Set this presenter as the output handler for the thread
	thread.SetOutputHandler(p)
	return p
}

// SetView sets the view to render the chat conversation.
// It initializes the view with the current session state.
func (p *ChatPresenter) SetView(view ui.ChatView) error {
	p.mu.Lock()
	p.view = view
	session := p.thread.GetSession()
	p.mu.Unlock()

	if session == nil {
		// No session yet, just set the view
		return nil
	}

	// Build ChatSessionUI from SweSession
	chatSession := p.buildChatSession(session)
	return view.Init(chatSession)
}

// SendUserMessage sends a user message to the chat session and starts processing.
func (p *ChatPresenter) SendUserMessage(message *ui.ChatMessageUI) error {
	p.mu.Lock()
	view := p.view
	p.mu.Unlock()

	// Add message to view
	if view != nil {
		if err := view.AddMessage(message); err != nil {
			return err
		}
	}

	// Send to thread (this adds to queue and starts processing)
	return p.thread.UserPrompt(message.Text)
}

// SaveUserMessage saves a user message to the chat session but doesn't start processing.
func (p *ChatPresenter) SaveUserMessage(message *ui.ChatMessageUI) error {
	p.mu.Lock()
	view := p.view
	p.mu.Unlock()

	// Add message to view
	if view != nil {
		if err := view.AddMessage(message); err != nil {
			return err
		}
	}

	// Add to thread queue without starting processing
	return p.thread.AddPrompt(message.Text)
}

// Pause pauses the chat session (i.e. stops processing).
func (p *ChatPresenter) Pause() error {
	return p.thread.Pause()
}

// Resume resumes the chat session (i.e. starts processing).
func (p *ChatPresenter) Resume() error {
	return p.thread.Resume()
}

// AddMarkdownChunk is called when new text chunk is generated by LLM.
// Implements core.SessionThreadOutput.
func (p *ChatPresenter) AddMarkdownChunk(markdown string) {
	p.mu.Lock()
	view := p.view

	// Create or update current assistant message
	if p.currentAssistantMessage == nil {
		p.messageCounter++
		p.currentAssistantMessage = &ui.ChatMessageUI{
			Id:    generateMessageID(p.messageCounter),
			Role:  ui.ChatRoleAssistant,
			Text:  markdown,
			Tools: []*ui.ToolUI{},
		}
		p.mu.Unlock()

		if view != nil {
			view.AddMessage(p.currentAssistantMessage)
			view.MoveToBottom()
		}
		return
	}

	// Append to existing message
	p.currentAssistantMessage.Text += markdown
	msg := p.currentAssistantMessage
	p.mu.Unlock()

	if view != nil {
		view.UpdateMessage(msg)
		view.MoveToBottom()
	}
}

// AddToolCallStart is called when tool call is started but not fully parsed yet.
// Implements core.SessionThreadOutput.
func (p *ChatPresenter) AddToolCallStart(call *tool.ToolCall) {
	p.mu.Lock()
	view := p.view

	// Ensure we have a current assistant message
	if p.currentAssistantMessage == nil {
		p.messageCounter++
		p.currentAssistantMessage = &ui.ChatMessageUI{
			Id:    generateMessageID(p.messageCounter),
			Role:  ui.ChatRoleAssistant,
			Text:  "",
			Tools: []*ui.ToolUI{},
		}
		p.mu.Unlock()

		if view != nil {
			view.AddMessage(p.currentAssistantMessage)
		}
		p.mu.Lock()
	}

	// Create tool state
	p.toolCallCounter++
	toolState := &ui.ToolUI{
		Id:     call.ID,
		Status: ui.ToolStatusStarted,
		Name:   call.Function,
	}

	// Add to current message's tools
	p.currentAssistantMessage.Tools = append(p.currentAssistantMessage.Tools, toolState)
	msg := p.currentAssistantMessage
	p.mu.Unlock()

	if view != nil {
		view.UpdateMessage(msg)
		view.MoveToBottom()
	}
}

// AddToolCallDetails is called when tool call is fully or partially parsed.
// Implements core.SessionThreadOutput.
func (p *ChatPresenter) AddToolCallDetails(call *tool.ToolCall) {
	p.mu.Lock()
	view := p.view

	// Find and update the tool in current message
	if p.currentAssistantMessage != nil {
		for _, t := range p.currentAssistantMessage.Tools {
			if t.Id == call.ID {
				t.Name = call.Function
				t.Status = ui.ToolStatusExecuting
				t.Message = formatToolArguments(call)
				t.Props = buildToolProps(call)
				break
			}
		}
	}
	p.mu.Unlock()

	if view != nil {
		// Find the tool state to update
		p.mu.Lock()
		var toolState *ui.ToolUI
		if p.currentAssistantMessage != nil {
			for _, t := range p.currentAssistantMessage.Tools {
				if t.Id == call.ID {
					toolState = t
					break
				}
			}
		}
		p.mu.Unlock()

		if toolState != nil {
			view.UpdateTool(toolState)
			view.MoveToBottom()
		}
	}
}

// AddToolCallResult is called when tool call is completed.
// Implements core.SessionThreadOutput.
func (p *ChatPresenter) AddToolCallResult(result *tool.ToolResponse) {
	p.mu.Lock()
	view := p.view

	// Find and update the tool in current message
	var toolState *ui.ToolUI
	if p.currentAssistantMessage != nil {
		for _, t := range p.currentAssistantMessage.Tools {
			if t.Id == result.Call.ID {
				if result.Error != nil {
					t.Status = ui.ToolStatusFailed
					t.Message = result.Error.Error()
				} else {
					t.Status = ui.ToolStatusSucceeded
				}
				toolState = t
				break
			}
		}
	}
	p.mu.Unlock()

	if view != nil && toolState != nil {
		view.UpdateTool(toolState)
		view.MoveToBottom()
	}
}

// RunFinished is called when the session Run() loop is finished.
// Implements core.SessionThreadOutput.
func (p *ChatPresenter) RunFinished(err error) {
	p.mu.Lock()
	// Reset current assistant message for next run
	p.currentAssistantMessage = nil
	p.mu.Unlock()
}

// buildChatSession converts a SweSession to a ui.ChatSessionUI.
func (p *ChatPresenter) buildChatSession(session *core.SweSession) *ui.ChatSessionUI {
	chatSession := &ui.ChatSessionUI{
		Id:       session.ID(),
		Model:    session.Model(),
		WorkDir:  session.GetState().Info.WorkDir,
		Messages: []*ui.ChatMessageUI{},
	}

	// Set role name if available
	if session.Role() != nil {
		chatSession.Role = session.Role().Name
	}

	// Convert messages
	for _, msg := range session.ChatMessages() {
		chatMsg := p.convertMessage(msg)
		if chatMsg != nil {
			chatSession.Messages = append(chatSession.Messages, chatMsg)
		}
	}

	return chatSession
}

// convertMessage converts a models.ChatMessage to a ui.ChatMessageUI.
func (p *ChatPresenter) convertMessage(msg *models.ChatMessage) *ui.ChatMessageUI {
	// Skip system messages
	if msg.Role == models.ChatRoleSystem {
		return nil
	}

	p.messageCounter++
	chatMsg := &ui.ChatMessageUI{
		Id:    generateMessageID(p.messageCounter),
		Text:  msg.GetText(),
		Tools: []*ui.ToolUI{},
	}

	// Set role
	switch msg.Role {
	case models.ChatRoleAssistant:
		chatMsg.Role = ui.ChatRoleAssistant
	case models.ChatRoleUser:
		chatMsg.Role = ui.ChatRoleUser
	default:
		chatMsg.Role = ui.ChatRoleUser
	}

	// Convert tool calls
	for _, tc := range msg.GetToolCalls() {
		p.toolCallCounter++
		toolState := &ui.ToolUI{
			Id:      tc.ID,
			Status:  ui.ToolStatusSucceeded, // Historical tool calls are completed
			Name:    tc.Function,
			Message: formatToolArguments(tc),
			Props:   buildToolProps(tc),
		}
		chatMsg.Tools = append(chatMsg.Tools, toolState)
	}

	return chatMsg
}

// generateMessageID generates a unique message ID.
// TODO use uuid instead
func generateMessageID(counter int) string {
	return string(rune('0'+counter%10)) + "-msg-" + string(rune('a'+counter/10%26))
}

// formatToolArguments formats tool arguments for display.
func formatToolArguments(call *tool.ToolCall) string {
	if call.Arguments.IsNil() {
		return ""
	}
	// Return a simple string representation
	if obj := call.Arguments.Object(); obj != nil {
		// Get first string argument as message
		for _, v := range obj {
			if s := v.AsString(); s != "" {
				return s
			}
		}
	}
	return ""
}

// buildToolProps builds the Props array for a tool state.
func buildToolProps(call *tool.ToolCall) [][]string {
	if call.Arguments.IsNil() {
		return nil
	}

	obj := call.Arguments.Object()
	if obj == nil {
		return nil
	}

	props := make([][]string, 0, len(obj))
	for k, v := range obj {
		props = append(props, []string{k, formatToolValue(v)})
	}
	return props
}

// formatToolValue formats a tool value for display.
func formatToolValue(v tool.ToolValue) string {
	switch v.Type() {
	case "string":
		return v.AsString()
	case "number":
		return string(rune('0' + int(v.AsInt())%10))
	case "bool":
		if v.AsBool() {
			return "true"
		}
		return "false"
	default:
		return ""
	}
}
