package presenter

import (
	"sync"

	"github.com/rlewczuk/csw/pkg/core"
	"github.com/rlewczuk/csw/pkg/models"
	"github.com/rlewczuk/csw/pkg/tool"
	"github.com/rlewczuk/csw/pkg/ui"
)

// ChatPresenter implements ui.IChatPresenter and core.SessionThreadOutput.
// It acts as a bridge between the SessionThread and the IChatView,
// translating session events into UI updates.
type ChatPresenter struct {
	mu     sync.Mutex
	view   ui.IChatView
	thread *core.SessionThread
	system *core.SweSystem

	// Tracking state for current run
	currentAssistantMessage *ui.ChatMessageUI
	messageCounter          int
	toolCallCounter         int
}

// NewChatPresenter creates a new ChatPresenter with the given system and session thread.
func NewChatPresenter(system *core.SweSystem, thread *core.SessionThread) *ChatPresenter {
	p := &ChatPresenter{
		system: system,
		thread: thread,
	}
	// Set this presenter as the output handler for the thread
	thread.SetOutputHandler(p)
	return p
}

// SetView sets the view to render the chat conversation.
// It initializes the view with the current session state.
func (p *ChatPresenter) SetView(view ui.IChatView) error {
	p.mu.Lock()
	p.view = view
	session := p.thread.GetSession()
	p.mu.Unlock()

	if session == nil {
		// No session yet, just set the view
		return nil
	}

	// Build ChatSessionUI from SweSession
	chatSession := p.buildChatSession(session)
	return view.Init(chatSession)
}

// SendUserMessage sends a user message to the chat session and starts processing.
func (p *ChatPresenter) SendUserMessage(message *ui.ChatMessageUI) error {
	p.mu.Lock()
	view := p.view
	p.mu.Unlock()

	// Add message to view
	if view != nil {
		if err := view.AddMessage(message); err != nil {
			return err
		}
	}

	// Send to thread (this adds to queue and starts processing)
	return p.thread.UserPrompt(message.Text)
}

// SaveUserMessage saves a user message to the chat session but doesn't start processing.
func (p *ChatPresenter) SaveUserMessage(message *ui.ChatMessageUI) error {
	p.mu.Lock()
	view := p.view
	p.mu.Unlock()

	// Add message to view
	if view != nil {
		if err := view.AddMessage(message); err != nil {
			return err
		}
	}

	// Add to thread queue without starting processing
	return p.thread.AddPrompt(message.Text)
}

// Pause pauses the chat session (i.e. stops processing).
func (p *ChatPresenter) Pause() error {
	return p.thread.Pause()
}

// Resume resumes the chat session (i.e. starts processing).
func (p *ChatPresenter) Resume() error {
	return p.thread.Resume()
}

// PermissionResponse sends user response to permission query.
func (p *ChatPresenter) PermissionResponse(response string) error {
	return p.thread.PermissionResponse(response)
}

// SetModel sets the model used for the chat session.
func (p *ChatPresenter) SetModel(model string) error {
	return p.thread.SetModel(model)
}

// OnPermissionQuery is called when the session encounters a permission query.
// Implements core.SessionThreadOutput.
func (p *ChatPresenter) OnPermissionQuery(query *tool.ToolPermissionsQuery) {
	p.mu.Lock()
	view := p.view
	p.mu.Unlock()

	if view != nil {
		uiQuery := &ui.PermissionQueryUI{
			Id:      query.Id,
			Title:   query.Title,
			Details: query.Details,
			Options: query.Options,
		}
		// view.QueryPermission returns error but we can't return it here.
		// We should probably log it or ignore it (UI failure).
		_ = view.QueryPermission(uiQuery)
	}
}

// AddAssistantMessage is called when a full assistant message is generated by LLM.
// Implements core.SessionThreadOutput.
func (p *ChatPresenter) AddAssistantMessage(text string, thinking string) {
	p.mu.Lock()
	p.messageCounter++
	msg := &ui.ChatMessageUI{
		Id:       generateMessageID(p.messageCounter),
		Role:     ui.ChatRoleAssistant,
		Text:     text,
		Thinking: thinking,
		Tools:    []*ui.ToolUI{},
	}
	p.currentAssistantMessage = msg
	view := p.view
	p.mu.Unlock()

	if view != nil {
		_ = view.AddMessage(msg)
		_ = view.MoveToBottom()
	}
}

// AddToolCall is called when assistant requests a tool call.
// Implements core.SessionThreadOutput.
func (p *ChatPresenter) AddToolCall(call *tool.ToolCall) {
	if call == nil {
		return
	}

	p.mu.Lock()
	view := p.view

	if p.currentAssistantMessage == nil {
		p.messageCounter++
		p.currentAssistantMessage = &ui.ChatMessageUI{
			Id:    generateMessageID(p.messageCounter),
			Role:  ui.ChatRoleAssistant,
			Tools: []*ui.ToolUI{},
		}
	}

	var toolState *ui.ToolUI
	for _, t := range p.currentAssistantMessage.Tools {
		if t.Id == call.ID {
			toolState = t
			break
		}
	}
	if toolState == nil {
		p.toolCallCounter++
		toolState = &ui.ToolUI{Id: call.ID}
		p.currentAssistantMessage.Tools = append(p.currentAssistantMessage.Tools, toolState)
	}

	toolState.Name = call.Function
	toolState.Status = ui.ToolStatusExecuting
	toolState.Message = formatToolArguments(call)
	toolState.Props = buildToolProps(call)

	msg := p.currentAssistantMessage
	p.mu.Unlock()

	if view != nil {
		_ = view.UpdateMessage(msg)
		_ = view.UpdateTool(toolState)
		_ = view.MoveToBottom()
	}
}

// AddToolCallResult is called when tool call is completed.
// Implements core.SessionThreadOutput.
func (p *ChatPresenter) AddToolCallResult(result *tool.ToolResponse) {
	p.mu.Lock()
	view := p.view

	// Find and update the tool in current message
	var toolState *ui.ToolUI
	if p.currentAssistantMessage != nil {
		for _, t := range p.currentAssistantMessage.Tools {
			if t.Id == result.Call.ID {
				if result.Error != nil {
					t.Status = ui.ToolStatusFailed
					t.Message = result.Error.Error()
				} else {
					t.Status = ui.ToolStatusSucceeded
				}
				// Get the render result from the tool
				if p.system != nil && p.system.Tools != nil {
					if toolImpl, err := p.system.Tools.Get(result.Call.Function); err == nil {
						summary, details, meta := toolImpl.Render(result.Call)
						t.Summary = summary
						t.Details = details
						t.Meta = meta
					}
				}
				toolState = t
				break
			}
		}
	}
	p.mu.Unlock()

	if view != nil && toolState != nil {
		view.UpdateTool(toolState)
		view.MoveToBottom()
	}
}

// RunFinished is called when the session Run() loop is finished.
// Implements core.SessionThreadOutput.
func (p *ChatPresenter) RunFinished(err error) {
	p.mu.Lock()
	// Reset current assistant message for next run
	p.currentAssistantMessage = nil
	p.mu.Unlock()
}

// OnRateLimitError is called when the session encounters a rate limit error.
// Implements core.SessionThreadOutput.
// Currently this is a no-op as rate limit errors are handled with retry in the session.
// The UI is notified via RunFinished if all retries are exhausted.
func (p *ChatPresenter) OnRateLimitError(retryAfterSeconds int) {
	// Rate limit is handled with automatic retry in the session.
	// If the UI needs to display this, it would be done through RunFinished
	// when all retries are exhausted.
}

// buildChatSession converts a SweSession to a ui.ChatSessionUI.
func (p *ChatPresenter) buildChatSession(session *core.SweSession) *ui.ChatSessionUI {
	chatSession := &ui.ChatSessionUI{
		Id:       session.ID(),
		Model:    session.Model(),
		WorkDir:  session.GetState().Info.WorkDir,
		Messages: []*ui.ChatMessageUI{},
	}

	// Set role name if available
	if session.Role() != nil {
		chatSession.Role = session.Role().Name
	}

	// Convert messages
	for _, msg := range session.ChatMessages() {
		chatMsg := p.convertMessage(msg)
		if chatMsg != nil {
			chatSession.Messages = append(chatSession.Messages, chatMsg)
		}
	}

	return chatSession
}

// convertMessage converts a models.ChatMessage to a ui.ChatMessageUI.
func (p *ChatPresenter) convertMessage(msg *models.ChatMessage) *ui.ChatMessageUI {
	// Skip system messages
	if msg.Role == models.ChatRoleSystem {
		return nil
	}

	p.messageCounter++
	chatMsg := &ui.ChatMessageUI{
		Id:    generateMessageID(p.messageCounter),
		Text:  msg.GetText(),
		Tools: []*ui.ToolUI{},
	}

	// Set role
	switch msg.Role {
	case models.ChatRoleAssistant:
		chatMsg.Role = ui.ChatRoleAssistant
	case models.ChatRoleUser:
		chatMsg.Role = ui.ChatRoleUser
	default:
		chatMsg.Role = ui.ChatRoleUser
	}

	// Convert tool calls
	for _, tc := range msg.GetToolCalls() {
		p.toolCallCounter++
		toolState := &ui.ToolUI{
			Id:      tc.ID,
			Status:  ui.ToolStatusSucceeded, // Historical tool calls are completed
			Name:    tc.Function,
			Message: formatToolArguments(tc),
			Props:   buildToolProps(tc),
		}
		chatMsg.Tools = append(chatMsg.Tools, toolState)
	}

	return chatMsg
}

// generateMessageID generates a unique message ID.
// TODO use uuid instead
func generateMessageID(counter int) string {
	return string(rune('0'+counter%10)) + "-msg-" + string(rune('a'+counter/10%26))
}

// formatToolArguments formats tool arguments for display.
func formatToolArguments(call *tool.ToolCall) string {
	if call.Arguments.IsNil() {
		return ""
	}
	// Return a simple string representation
	if obj := call.Arguments.Object(); obj != nil {
		// Get first string argument as message
		for _, v := range obj {
			if s := v.AsString(); s != "" {
				return s
			}
		}
	}
	return ""
}

// buildToolProps builds the Props array for a tool state.
func buildToolProps(call *tool.ToolCall) [][]string {
	if call.Arguments.IsNil() {
		return nil
	}

	obj := call.Arguments.Object()
	if obj == nil {
		return nil
	}

	props := make([][]string, 0, len(obj))
	for k, v := range obj {
		props = append(props, []string{k, formatToolValue(v)})
	}
	return props
}

// formatToolValue formats a tool value for display.
func formatToolValue(v tool.ToolValue) string {
	switch v.Type() {
	case "string":
		return v.AsString()
	case "number":
		return string(rune('0' + int(v.AsInt())%10))
	case "bool":
		if v.AsBool() {
			return "true"
		}
		return "false"
	default:
		return ""
	}
}
