package ui

import "github.com/codesnort/codesnort-swe/pkg/tool"

// This package provides UI output handling interfaces and implementations.
// The core interfaces (SessionOutputHandler, SweUiFactory) are defined in pkg/core
// to avoid circular dependencies.

// SessionOutputHandler is an interface for handling output from the session.
// Defined here to avoid circular dependency with pkg/ui.
type SessionOutputHandler interface {
	// AddMarkdownChunk is called when new text chunk is generated by LLM.
	AddMarkdownChunk(markdown string)

	// AddToolCallStart is called when tool call is started but not fully parsed yet,
	// so we don't know any details about it yet.
	AddToolCallStart(call *tool.ToolCall)

	// AddToolCallDetails is called when tool call is fully or partially parsed and we know more details about it.
	// This can be called multiple times for the same tool call as new chunks are received,
	// UI is responsible for merging them into existing view.
	AddToolCallDetails(call *tool.ToolCall)

	// AddToolCallResult is called when tool call is completed and we have the final result.
	// This also includes errors if tool call failed, UI is responsible
	// for checking error status and displaying either result or error.
	AddToolCallResult(result *tool.ToolResponse)
}

// SweUiFactory is an interface for creating UI handlers for the session.
type SweUiFactory interface {
	// NewSessionOutputHandler creates a new output handler for the session.
	NewSessionOutputHandler() SessionOutputHandler
}
