package ui

import "github.com/codesnort/codesnort-swe/pkg/tool"

// This package provides UI output handling interfaces and implementations.
// The core interfaces (SessionOutputHandler, SweUiFactory) are defined in pkg/core
// to avoid circular dependencies.

// SessionInputHandler is an interface for handling input to the session.
// In single-process (eg. TUI) environment it will be called directly from user interface code.
// In multi-process (server) environment it will be called via REST API or remote procedure call.
// It is called by UI input events and can be used to inject user input into the session.
// Note: all methods are non-blocking, input handler implementation is responsible for
// maintaining thread, context and cancellation safety.
type SessionInputHandler interface {
	// UserPrompt is called when user input via prompt box is received.
	// If there was running task in progress in session, it is interrupted and
	// user prompt is added to the conversation, then processing is resumed.
	UserPrompt(input string) error

	// Interrupt is called when user interrupts the current task.
	Interrupt() error
}

// SessionOutputHandler is an interface for handling output from the session.
// Defined here to avoid circular dependency with pkg/ui.
type SessionOutputHandler interface {
	// AddMarkdownChunk is called when new text chunk is generated by LLM.
	AddMarkdownChunk(markdown string)

	// AddToolCallStart is called when tool call is started but not fully parsed yet,
	// so we don't know any details about it yet.
	AddToolCallStart(call *tool.ToolCall)

	// AddToolCallDetails is called when tool call is fully or partially parsed and we know more details about it.
	// This can be called multiple times for the same tool call as new chunks are received,
	// UI is responsible for merging them into existing view.
	AddToolCallDetails(call *tool.ToolCall)

	// AddToolCallResult is called when tool call is completed and we have the final result.
	// This also includes errors if tool call failed, UI is responsible
	// for checking error status and displaying either result or error.
	AddToolCallResult(result *tool.ToolResponse)

	// RunFinished is called when the session Run() loop is finished.
	// This is called either when the session completes successfully (err == nil)
	// or when it encounters an error (err != nil).
	RunFinished(err error)
}
