package core

import (
	"context"
	"fmt"
	"strings"
	"sync"

	"github.com/codesnort/codesnort-swe/pkg/models"
	"github.com/codesnort/codesnort-swe/pkg/shared"
	"github.com/codesnort/codesnort-swe/pkg/tool"
	"github.com/codesnort/codesnort-swe/pkg/vfs"
)

// SessionThreadInput is an interface for handling input to the session.
// In single-process (eg. TUI) environment it will be called directly from user interface code.
// In multi-process (server) environment it will be called via REST API or remote procedure call.
// It is called by UI input events and can be used to inject user input into the session.
// Note: all methods are non-blocking, input handler implementation is responsible for
// maintaining thread, context and cancellation safety.
type SessionThreadInput interface {
	// UserPrompt is called when user input via prompt box is received.
	// If there was running task in progress in session, it is interrupted and
	// user prompt is added to the conversation, then processing is resumed.
	UserPrompt(input string) error

	// Interrupt is called when user interrupts the current task.
	Interrupt() error
}

// SessionThreadOutput is an interface for handling output from the session.
type SessionThreadOutput interface {
	// AddMarkdownChunk is called when new text chunk is generated by LLM.
	AddMarkdownChunk(markdown string)

	// AddToolCallStart is called when tool call is started but not fully parsed yet,
	// so we don't know any details about it yet.
	AddToolCallStart(call *tool.ToolCall)

	// AddToolCallDetails is called when tool call is fully or partially parsed and we know more details about it.
	// This can be called multiple times for the same tool call as new chunks are received,
	// UI is responsible for merging them into existing view.
	AddToolCallDetails(call *tool.ToolCall)

	// AddToolCallResult is called when tool call is completed and we have the final result.
	// This also includes errors if tool call failed, UI is responsible
	// for checking error status and displaying either result or error.
	AddToolCallResult(result *tool.ToolResponse)

	// RunFinished is called when the session Run() loop is finished.
	// This is called either when the session completes successfully (err == nil)
	// or when it encounters an error (err != nil).
	RunFinished(err error)

	// OnPermissionQuery is called when the session encounters a permission query.
	OnPermissionQuery(query *tool.ToolPermissionsQuery)
}

// SessionThread manages a session thread with input and context management.
// It ensures that SweSession is only called from a background thread and that
// at most one session loop is running at a time.
type SessionThread struct {
	system        *SweSystem
	outputHandler SessionThreadOutput

	mu                     sync.Mutex
	session                *SweSession
	sessionRunning         bool
	backgroundCtx          context.Context
	cancelFunc             context.CancelFunc
	inputQueue             []string
	interruptPending       bool
	paused                 bool
	resumePending          bool
	pendingPermissionQuery *tool.ToolPermissionsQuery
}

// NewSessionThread creates a new SessionThread with the given system and output handler.
func NewSessionThread(system *SweSystem, outputHandler SessionThreadOutput) *SessionThread {
	return &SessionThread{
		system:        system,
		outputHandler: outputHandler,
		inputQueue:    make([]string, 0),
	}
}

// NewSessionThreadWithSession creates a new SessionThread with an existing session.
// This allows creating a new thread/presenter while preserving session state and messages.
func NewSessionThreadWithSession(system *SweSystem, session *SweSession, outputHandler SessionThreadOutput) *SessionThread {
	// Update the session's output handler to the new one
	session.outputHandler = outputHandler
	return &SessionThread{
		system:        system,
		session:       session,
		outputHandler: outputHandler,
		inputQueue:    make([]string, 0),
	}
}

// GetSession returns the current session. Safe to call from any thread.
func (c *SessionThread) GetSession() *SweSession {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.session
}

// UserPrompt adds a user prompt to the session and starts processing if not already running.
// This method is non-blocking and thread-safe.
func (c *SessionThread) UserPrompt(input string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	// Initialize session if not already created
	if c.session == nil {
		return fmt.Errorf("SessionThread.UserPrompt() [session.go]: session not initialized, call StartSession first")
	}

	// Add to input queue
	c.inputQueue = append(c.inputQueue, input)

	// If session is not running, start it
	if !c.sessionRunning {
		c.startSessionLocked()
	}

	return nil
}

// Interrupt cancels the current running session.
// This method is non-blocking and thread-safe.
func (c *SessionThread) Interrupt() error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if !c.sessionRunning {
		return fmt.Errorf("SessionThread.Interrupt() [session.go]: no session running to interrupt")
	}

	c.interruptPending = true
	if c.cancelFunc != nil {
		c.cancelFunc()
	}

	return nil
}

// AddPrompt adds a user prompt to the session without starting processing.
// This method is non-blocking and thread-safe.
// Use Resume() to start processing the queued prompts.
func (c *SessionThread) AddPrompt(input string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if c.session == nil {
		return fmt.Errorf("SessionThread.AddPrompt() [session.go]: session not initialized, call StartSession first")
	}

	// Add to input queue
	c.inputQueue = append(c.inputQueue, input)

	return nil
}

// Pause stops the current session processing without signaling an error.
// The queue is preserved and can be resumed with Resume().
// This method is non-blocking and thread-safe.
func (c *SessionThread) Pause() error {
	c.mu.Lock()
	defer c.mu.Unlock()

	c.paused = true

	if c.sessionRunning && c.cancelFunc != nil {
		c.cancelFunc()
	}

	return nil
}

// Resume starts processing the queued prompts if not already running.
// This method is non-blocking and thread-safe.
func (c *SessionThread) Resume() error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if c.session == nil {
		return fmt.Errorf("SessionThread.Resume() [session.go]: session not initialized, call StartSession first")
	}

	c.paused = false

	// Start processing if not already running and there are items in the queue
	if !c.sessionRunning && len(c.inputQueue) > 0 {
		c.startSessionLocked()
	}

	return nil
}

// IsPaused returns true if the session is paused.
func (c *SessionThread) IsPaused() bool {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.paused
}

// IsRunning returns true if the session loop is currently running.
func (c *SessionThread) IsRunning() bool {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.sessionRunning
}

// SetOutputHandler sets the output handler for the controller.
// This method is thread-safe and can be called before or after StartSession.
// If called after StartSession, it will update the output handler for the existing session.
func (c *SessionThread) SetOutputHandler(handler SessionThreadOutput) {
	c.mu.Lock()
	defer c.mu.Unlock()

	c.outputHandler = handler
	if c.session != nil {
		c.session.outputHandler = handler
	}
}

// PermissionResponse handles the user's response to a permission query.
func (c *SessionThread) PermissionResponse(response string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if c.pendingPermissionQuery == nil {
		return fmt.Errorf("SessionThread.PermissionResponse() [session.go]: no pending permission query")
	}

	query := c.pendingPermissionQuery
	c.pendingPermissionQuery = nil

	// Update privileges based on response
	if err := c.session.UpdatePermission(query, response); err != nil {
		return err
	}

	// Resume session
	c.paused = false
	c.resumePending = true
	if !c.sessionRunning {
		c.startSessionLocked()
	}

	return nil
}

// StartSession initializes a new session with the given model.
// This method is non-blocking and thread-safe.
func (c *SessionThread) StartSession(model string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if c.session != nil {
		return fmt.Errorf("SessionThread.StartSession() [session.go]: session already exists")
	}

	session, err := c.system.NewSession(model, c.outputHandler)
	if err != nil {
		return err
	}

	c.session = session
	return nil
}

// startSessionLocked starts the background session loop.
// Must be called with c.mu held.
func (c *SessionThread) startSessionLocked() {
	if c.sessionRunning {
		return
	}

	c.sessionRunning = true
	c.backgroundCtx, c.cancelFunc = context.WithCancel(context.Background())

	go c.runSessionLoop()
}

// runSessionLoop is the background thread that processes the session.
func (c *SessionThread) runSessionLoop() {
	ctx := c.backgroundCtx

	defer func() {
		c.mu.Lock()
		c.sessionRunning = false
		c.backgroundCtx = nil
		c.cancelFunc = nil
		c.mu.Unlock()
	}()

	for {
		// Get next input from queue
		c.mu.Lock()
		if len(c.inputQueue) == 0 {
			if c.resumePending {
				c.resumePending = false
				c.interruptPending = false
				c.mu.Unlock()

				// Run the session without new input (processing pending state/tools)
				err := c.session.Run(ctx)
				if err != nil {
					// Handle session error (which could be another permission query)
					if permErr, ok := err.(*tool.ToolPermissionsQuery); ok {
						c.mu.Lock()
						c.pendingPermissionQuery = permErr
						c.paused = true
						c.mu.Unlock()

						c.outputHandler.OnPermissionQuery(permErr)
						return
					}
					c.outputHandler.RunFinished(err)
					return
				}

				// If successful, check if we need to continue loop (e.g. check queue again)
				c.mu.Lock()
				wasInterrupted := c.interruptPending
				wasPaused := c.paused
				c.mu.Unlock()

				if wasPaused {
					c.outputHandler.RunFinished(nil)
					return
				}
				if wasInterrupted {
					c.outputHandler.RunFinished(fmt.Errorf("SessionThread.runSessionLoop() [session.go]: interrupted"))
					return
				}

				// Continue loop to check for more input
				continue
			}

			// No more input, stop the loop
			c.mu.Unlock()
			c.outputHandler.RunFinished(nil)
			return
		}

		// Check if paused
		if c.paused {
			c.mu.Unlock()
			c.outputHandler.RunFinished(nil)
			return
		}

		input := c.inputQueue[0]
		c.inputQueue = c.inputQueue[1:]
		c.interruptPending = false
		c.mu.Unlock()

		// Add user prompt to session (this is safe because we're in the background thread)
		err := c.session.UserPrompt(input)
		if err != nil {
			c.outputHandler.RunFinished(err)
			return
		}

		// Run the session
		err = c.session.Run(ctx)

		// Check for permission query
		if permErr, ok := err.(*tool.ToolPermissionsQuery); ok {
			c.mu.Lock()
			c.pendingPermissionQuery = permErr
			c.paused = true
			c.mu.Unlock()

			c.outputHandler.OnPermissionQuery(permErr)
			return
		}

		// Check if we were interrupted or paused
		c.mu.Lock()
		wasInterrupted := c.interruptPending
		wasPaused := c.paused
		c.mu.Unlock()

		if wasPaused {
			// Paused cleanly, no error
			c.outputHandler.RunFinished(nil)
			return
		}

		if wasInterrupted {
			c.outputHandler.RunFinished(fmt.Errorf("SessionThread.runSessionLoop() [session.go]: interrupted"))
			return
		}

		if err != nil {
			c.outputHandler.RunFinished(err)
			return
		}
	}
}

type SweSession struct {
	id            string
	system        *SweSystem
	provider      models.ModelProvider
	model         string
	messages      []*models.ChatMessage
	role          *AgentRole
	VFS           vfs.VFS
	Tools         *tool.ToolRegistry
	outputHandler SessionThreadOutput
	workDir       string
}

// Prompt adds user prompt to the conversation and starts processing if processing is not already in progress.
// If processing is already in progress, if will be added at the end of conversation after current LLM request is completed,
// its tool calls are executed etc. Returns immediately.
func (s *SweSession) UserPrompt(prompt string) error {
	s.messages = append(s.messages, models.NewTextMessage(models.ChatRoleUser, prompt))
	return nil
}

func (s *SweSession) Run(ctx context.Context) error {
	chatModel := s.provider.ChatModel(s.model, nil)
	tools := s.system.Tools.ListInfo()

	// Keep processing until the assistant doesn't make any tool calls
	for {
		// Check for pending tool calls from previous run (e.g. after permission grant)
		if len(s.messages) > 0 {
			lastMsg := s.messages[len(s.messages)-1]
			if lastMsg.Role == models.ChatRoleAssistant {
				toolCalls := lastMsg.GetToolCalls()
				if len(toolCalls) > 0 {
					// Execute pending tools
					if err := s.executeToolCalls(toolCalls); err != nil {
						return err
					}
				}
			}
		}

		// Use streaming chat API
		stream := chatModel.ChatStream(ctx, s.messages, nil, tools)

		// Accumulate the response from the stream
		responseMsg := &models.ChatMessage{
			Role:  models.ChatRoleAssistant,
			Parts: []models.ChatMessagePart{},
		}

		// Track tool calls we've seen to handle start events
		seenToolCalls := make(map[string]bool)

		for fragment := range stream {
			// Merge the fragment parts into the accumulated response
			for _, part := range fragment.Parts {
				responseMsg.Parts = append(responseMsg.Parts, part)

				// Notify UI handler about the fragment
				if s.outputHandler != nil {
					if part.Text != "" {
						s.outputHandler.AddMarkdownChunk(part.Text)
					}
					if part.ToolCall != nil {
						// Send start event if this is the first time we see this tool call
						if !seenToolCalls[part.ToolCall.ID] {
							s.outputHandler.AddToolCallStart(part.ToolCall)
							seenToolCalls[part.ToolCall.ID] = true
						}
						// Always send details event as chunks arrive
						s.outputHandler.AddToolCallDetails(part.ToolCall)
					}
				}
			}
		}

		// Add the accumulated response to messages
		s.messages = append(s.messages, responseMsg)

		// Check if there are any tool calls in the response
		toolCalls := responseMsg.GetToolCalls()
		if len(toolCalls) == 0 {
			// No tool calls, we're done
			break
		}

		// Execute tool calls
		if err := s.executeToolCalls(toolCalls); err != nil {
			return err
		}
	}

	return nil
}

// executeToolCalls executes the given tool calls and appends the results to the conversation.
func (s *SweSession) executeToolCalls(toolCalls []*tool.ToolCall) error {
	toolResponses := make([]*tool.ToolResponse, 0, len(toolCalls))
	for _, toolCall := range toolCalls {
		// Use s.Tools which might have access control wrappers
		response := s.Tools.Execute(*toolCall)

		// Check for permission query
		if _, ok := response.Error.(*tool.ToolPermissionsQuery); ok {
			return response.Error
		}

		toolResponses = append(toolResponses, &response)

		// Notify UI handler about tool result
		if s.outputHandler != nil {
			s.outputHandler.AddToolCallResult(&response)
		}
	}

	// Add tool responses to the conversation
	s.messages = append(s.messages, models.NewToolResponseMessage(toolResponses...))
	return nil
}

func (s *SweSession) ChatMessages() []*models.ChatMessage {
	return s.messages
}

// ID returns the unique identifier for this session.
func (s *SweSession) ID() string {
	return s.id
}

// Model returns the model name (without provider prefix) used for this session.
func (s *SweSession) Model() string {
	return s.model
}

// GetState returns the current agent state for this session.
func (s *SweSession) GetState() AgentState {
	return AgentState{
		Info: AgentStateCommonInfo{
			WorkDir: s.workDir,
		},
	}
}

// SetWorkDir sets the working directory for this session.
func (s *SweSession) SetWorkDir(dir string) {
	s.workDir = dir
}

// Role returns the current agent role for this session.
func (s *SweSession) Role() *AgentRole {
	return s.role
}

// SetRole changes the agent role for this session.
// It updates the VFS and Tools with access controls based on the new role,
// and adds or updates the system prompt at the beginning of the conversation.
func (s *SweSession) SetRole(roleName string) error {
	role, ok := s.system.Roles.Get(roleName)
	if !ok {
		return fmt.Errorf("SweSession.SetRole() [session.go]: role not found: %s", roleName)
	}

	// Store the new role
	s.role = &role

	// Wrap VFS with access control based on role privileges
	if role.VFSPrivileges != nil {
		s.VFS = vfs.NewAccessControlVFS(s.system.VFS, role.VFSPrivileges)
	} else {
		s.VFS = s.system.VFS
	}

	// Create a new tool registry for the session
	// We start with system tools
	s.Tools = tool.NewToolRegistry()
	for _, name := range s.system.Tools.List() {
		t, _ := s.system.Tools.Get(name)
		s.Tools.Register(name, t)
	}

	// Re-register VFS tools to use the session's VFS
	// This ensures that VFS access controls are respected
	s.Tools.Register("vfs.read", tool.NewVFSReadTool(s.VFS))
	s.Tools.Register("vfs.write", tool.NewVFSWriteTool(s.VFS))
	s.Tools.Register("vfs.delete", tool.NewVFSDeleteTool(s.VFS))
	s.Tools.Register("vfs.list", tool.NewVFSListTool(s.VFS))
	s.Tools.Register("vfs.move", tool.NewVFSMoveTool(s.VFS))

	// Create a new tool registry with access-controlled tools if needed
	if role.ToolsAccess != nil {
		s.Tools = wrapToolsWithAccessControl(s.Tools, role.ToolsAccess)
	}

	// Generate and update system prompt using the prompt generator
	if s.system.PromptGenerator != nil {
		state := s.GetState()
		renderedPrompt, err := s.system.PromptGenerator.GetPrompt([]string{"all"}, &role, &state)
		if err != nil {
			return fmt.Errorf("failed to generate system prompt: %w", err)
		}

		// Check if there's already a system message
		if len(s.messages) > 0 && s.messages[0].Role == models.ChatRoleSystem {
			// Replace the existing system message
			s.messages[0] = models.NewTextMessage(models.ChatRoleSystem, renderedPrompt)
		} else {
			// Insert system message at the beginning
			s.messages = append([]*models.ChatMessage{models.NewTextMessage(models.ChatRoleSystem, renderedPrompt)}, s.messages...)
		}
	}

	return nil
}

// UpdatePermission updates the permission for a tool or VFS operation based on user response.
func (s *SweSession) UpdatePermission(query *tool.ToolPermissionsQuery, response string) error {
	allow := strings.ToLower(response) == "allow"
	flag := shared.AccessDeny
	if allow {
		flag = shared.AccessAllow
	}

	if query.Meta != nil && query.Meta["type"] == "vfs" {
		path := query.Meta["path"]
		op := query.Meta["operation"]

		ac, ok := s.VFS.(*vfs.AccessControlVFS)
		if ok {
			ac.SetPermission(path, op, flag)
		}
	} else {
		// Tool permission
		toolName := query.Tool.Function

		// We need to find the AccessControlTool for this tool
		t, err := s.Tools.Get(toolName)
		if err != nil {
			return err
		}

		ac, ok := t.(*tool.AccessControlTool)
		if ok {
			// We set permission for this specific tool name
			ac.SetPermission(toolName, flag)
		}
	}
	return nil
}

// wrapToolsWithAccessControl creates a new tool registry with all tools wrapped in access control.
func wrapToolsWithAccessControl(registry *tool.ToolRegistry, privileges map[string]shared.AccessFlag) *tool.ToolRegistry {
	newRegistry := tool.NewToolRegistry()

	// Get all tool names from the original registry
	for _, name := range registry.List() {
		t, err := registry.Get(name)
		if err != nil {
			// This shouldn't happen since we just got the name from List()
			continue
		}

		// Wrap the tool with access control
		wrappedTool := tool.NewAccessControlTool(t, privileges)
		newRegistry.Register(name, wrappedTool)
	}

	return newRegistry
}
