package core

import (
	"context"
	"fmt"
	"sync"

	"github.com/codesnort/codesnort-swe/pkg/models"
	"github.com/codesnort/codesnort-swe/pkg/shared"
	"github.com/codesnort/codesnort-swe/pkg/tool"
	"github.com/codesnort/codesnort-swe/pkg/vfs"
)

// SessionThreadInput is an interface for handling input to the session.
// In single-process (eg. TUI) environment it will be called directly from user interface code.
// In multi-process (server) environment it will be called via REST API or remote procedure call.
// It is called by UI input events and can be used to inject user input into the session.
// Note: all methods are non-blocking, input handler implementation is responsible for
// maintaining thread, context and cancellation safety.
type SessionThreadInput interface {
	// UserPrompt is called when user input via prompt box is received.
	// If there was running task in progress in session, it is interrupted and
	// user prompt is added to the conversation, then processing is resumed.
	UserPrompt(input string) error

	// Interrupt is called when user interrupts the current task.
	Interrupt() error
}

// SessionThreadOutput is an interface for handling output from the session.
type SessionThreadOutput interface {
	// AddMarkdownChunk is called when new text chunk is generated by LLM.
	AddMarkdownChunk(markdown string)

	// AddToolCallStart is called when tool call is started but not fully parsed yet,
	// so we don't know any details about it yet.
	AddToolCallStart(call *tool.ToolCall)

	// AddToolCallDetails is called when tool call is fully or partially parsed and we know more details about it.
	// This can be called multiple times for the same tool call as new chunks are received,
	// UI is responsible for merging them into existing view.
	AddToolCallDetails(call *tool.ToolCall)

	// AddToolCallResult is called when tool call is completed and we have the final result.
	// This also includes errors if tool call failed, UI is responsible
	// for checking error status and displaying either result or error.
	AddToolCallResult(result *tool.ToolResponse)

	// RunFinished is called when the session Run() loop is finished.
	// This is called either when the session completes successfully (err == nil)
	// or when it encounters an error (err != nil).
	RunFinished(err error)
}

// SessionThread manages a session thread with input and context management.
// It ensures that SweSession is only called from a background thread and that
// at most one session loop is running at a time.
type SessionThread struct {
	system        *SweSystem
	outputHandler SessionThreadOutput

	mu               sync.Mutex
	session          *SweSession
	sessionRunning   bool
	backgroundCtx    context.Context
	cancelFunc       context.CancelFunc
	inputQueue       []string
	interruptPending bool
}

// NewSessionController creates a new SessionThread with the given system and output handler.
func NewSessionController(system *SweSystem, outputHandler SessionThreadOutput) *SessionThread {
	return &SessionThread{
		system:        system,
		outputHandler: outputHandler,
		inputQueue:    make([]string, 0),
	}
}

// GetSession returns the current session. Safe to call from any thread.
func (c *SessionThread) GetSession() *SweSession {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.session
}

// UserPrompt adds a user prompt to the session and starts processing if not already running.
// This method is non-blocking and thread-safe.
func (c *SessionThread) UserPrompt(input string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	// Initialize session if not already created
	if c.session == nil {
		return fmt.Errorf("session not initialized, call StartSession first")
	}

	// Add to input queue
	c.inputQueue = append(c.inputQueue, input)

	// If session is not running, start it
	if !c.sessionRunning {
		c.startSessionLocked()
	}

	return nil
}

// Interrupt cancels the current running session.
// This method is non-blocking and thread-safe.
func (c *SessionThread) Interrupt() error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if !c.sessionRunning {
		return fmt.Errorf("no session running to interrupt")
	}

	c.interruptPending = true
	if c.cancelFunc != nil {
		c.cancelFunc()
	}

	return nil
}

// SetOutputHandler sets the output handler for the controller.
// This method is thread-safe and can be called before or after StartSession.
// If called after StartSession, it will update the output handler for the existing session.
func (c *SessionThread) SetOutputHandler(handler SessionThreadOutput) {
	c.mu.Lock()
	defer c.mu.Unlock()

	c.outputHandler = handler
	if c.session != nil {
		c.session.outputHandler = handler
	}
}

// StartSession initializes a new session with the given model.
// This method is non-blocking and thread-safe.
func (c *SessionThread) StartSession(model string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if c.session != nil {
		return fmt.Errorf("session already exists")
	}

	session, err := c.system.NewSession(model, c.outputHandler)
	if err != nil {
		return err
	}

	c.session = session
	return nil
}

// startSessionLocked starts the background session loop.
// Must be called with c.mu held.
func (c *SessionThread) startSessionLocked() {
	if c.sessionRunning {
		return
	}

	c.sessionRunning = true
	c.backgroundCtx, c.cancelFunc = context.WithCancel(context.Background())

	go c.runSessionLoop()
}

// runSessionLoop is the background thread that processes the session.
func (c *SessionThread) runSessionLoop() {
	ctx := c.backgroundCtx

	defer func() {
		c.mu.Lock()
		c.sessionRunning = false
		c.backgroundCtx = nil
		c.cancelFunc = nil
		c.mu.Unlock()
	}()

	for {
		// Get next input from queue
		c.mu.Lock()
		if len(c.inputQueue) == 0 {
			// No more input, stop the loop
			c.mu.Unlock()
			c.outputHandler.RunFinished(nil)
			return
		}

		input := c.inputQueue[0]
		c.inputQueue = c.inputQueue[1:]
		c.interruptPending = false
		c.mu.Unlock()

		// Add user prompt to session (this is safe because we're in the background thread)
		err := c.session.UserPrompt(input)
		if err != nil {
			c.outputHandler.RunFinished(err)
			return
		}

		// Run the session
		err = c.session.Run(ctx)

		// Check if we were interrupted
		c.mu.Lock()
		wasInterrupted := c.interruptPending
		c.mu.Unlock()

		if wasInterrupted {
			c.outputHandler.RunFinished(fmt.Errorf("interrupted"))
			return
		}

		if err != nil {
			c.outputHandler.RunFinished(err)
			return
		}
	}
}

type SweSession struct {
	system        *SweSystem
	provider      models.ModelProvider
	model         string
	messages      []*models.ChatMessage
	role          *AgentRole
	VFS           vfs.VFS
	Tools         *tool.ToolRegistry
	outputHandler SessionThreadOutput
	workDir       string
}

// Prompt adds user prompt to the conversation and starts processing if processing is not already in progress.
// If processing is already in progress, if will be added at the end of conversation after current LLM request is completed,
// its tool calls are executed etc. Returns immediately.
func (s *SweSession) UserPrompt(prompt string) error {
	s.messages = append(s.messages, models.NewTextMessage(models.ChatRoleUser, prompt))
	return nil
}

func (s *SweSession) Run(ctx context.Context) error {
	chatModel := s.provider.ChatModel(s.model, nil)
	tools := s.system.Tools.ListInfo()

	// Keep processing until the assistant doesn't make any tool calls
	for {
		// Use streaming chat API
		stream := chatModel.ChatStream(ctx, s.messages, nil, tools)

		// Accumulate the response from the stream
		responseMsg := &models.ChatMessage{
			Role:  models.ChatRoleAssistant,
			Parts: []models.ChatMessagePart{},
		}

		// Track tool calls we've seen to handle start events
		seenToolCalls := make(map[string]bool)

		for fragment := range stream {
			// Merge the fragment parts into the accumulated response
			for _, part := range fragment.Parts {
				responseMsg.Parts = append(responseMsg.Parts, part)

				// Notify UI handler about the fragment
				if s.outputHandler != nil {
					if part.Text != "" {
						s.outputHandler.AddMarkdownChunk(part.Text)
					}
					if part.ToolCall != nil {
						// Send start event if this is the first time we see this tool call
						if !seenToolCalls[part.ToolCall.ID] {
							s.outputHandler.AddToolCallStart(part.ToolCall)
							seenToolCalls[part.ToolCall.ID] = true
						}
						// Always send details event as chunks arrive
						s.outputHandler.AddToolCallDetails(part.ToolCall)
					}
				}
			}
		}

		// Add the accumulated response to messages
		s.messages = append(s.messages, responseMsg)

		// Check if there are any tool calls in the response
		toolCalls := responseMsg.GetToolCalls()
		if len(toolCalls) == 0 {
			// No tool calls, we're done
			break
		}

		// Execute tool calls
		toolResponses := make([]*tool.ToolResponse, 0, len(toolCalls))
		for _, toolCall := range toolCalls {
			response := s.system.Tools.Execute(*toolCall)
			toolResponses = append(toolResponses, &response)

			// Notify UI handler about tool result
			if s.outputHandler != nil {
				s.outputHandler.AddToolCallResult(&response)
			}
		}

		// Add tool responses to the conversation
		s.messages = append(s.messages, models.NewToolResponseMessage(toolResponses...))
	}

	return nil
}

func (s *SweSession) ChatMessages() []*models.ChatMessage {
	return s.messages
}

// GetState returns the current agent state for this session.
func (s *SweSession) GetState() AgentState {
	return AgentState{
		Info: AgentStateCommonInfo{
			WorkDir: s.workDir,
		},
	}
}

// SetWorkDir sets the working directory for this session.
func (s *SweSession) SetWorkDir(dir string) {
	s.workDir = dir
}

// Role returns the current agent role for this session.
func (s *SweSession) Role() *AgentRole {
	return s.role
}

// SetRole changes the agent role for this session.
// It updates the VFS and Tools with access controls based on the new role,
// and adds or updates the system prompt at the beginning of the conversation.
func (s *SweSession) SetRole(roleName string) error {
	role, ok := s.system.Roles.Get(roleName)
	if !ok {
		return fmt.Errorf("role not found: %s", roleName)
	}

	// Store the new role
	s.role = &role

	// Wrap VFS with access control based on role privileges
	if role.VFSPrivileges != nil {
		s.VFS = vfs.NewAccessControlVFS(s.system.VFS, role.VFSPrivileges)
	} else {
		s.VFS = s.system.VFS
	}

	// Create a new tool registry with access-controlled tools
	if role.ToolsAccess != nil {
		s.Tools = wrapToolsWithAccessControl(s.system.Tools, role.ToolsAccess)
	} else {
		s.Tools = s.system.Tools
	}

	// Update system prompt by rendering the template with current state
	if role.SystemPrompt != "" {
		state := s.GetState()
		renderedPrompt, err := role.RenderSystemPrompt(state)
		if err != nil {
			return fmt.Errorf("failed to render system prompt: %w", err)
		}

		// Check if there's already a system message
		if len(s.messages) > 0 && s.messages[0].Role == models.ChatRoleSystem {
			// Replace the existing system message
			s.messages[0] = models.NewTextMessage(models.ChatRoleSystem, renderedPrompt)
		} else {
			// Insert system message at the beginning
			s.messages = append([]*models.ChatMessage{models.NewTextMessage(models.ChatRoleSystem, renderedPrompt)}, s.messages...)
		}
	}

	return nil
}

// wrapToolsWithAccessControl creates a new tool registry with all tools wrapped in access control.
func wrapToolsWithAccessControl(registry *tool.ToolRegistry, privileges map[string]shared.AccessFlag) *tool.ToolRegistry {
	newRegistry := tool.NewToolRegistry()

	// Get all tool names from the original registry
	for _, name := range registry.List() {
		t, err := registry.Get(name)
		if err != nil {
			// This shouldn't happen since we just got the name from List()
			continue
		}

		// Wrap the tool with access control
		wrappedTool := tool.NewAccessControlTool(t, privileges)
		newRegistry.Register(name, wrappedTool)
	}

	return newRegistry
}
