package core

import (
	"context"
	"fmt"
	"sync"

	"github.com/rlewczuk/csw/pkg/tool"
)

// SessionThreadInput is an interface for handling input to the session.
// In single-process (eg. TUI) environment it will be called directly from user interface code.
// In multi-process (server) environment it will be called via REST API or remote procedure call.
// It is called by UI input events and can be used to inject user input into the session.
// Note: all methods are non-blocking, input handler implementation is responsible for
// maintaining thread, context and cancellation safety.
type SessionThreadInput interface {
	// UserPrompt is called when user input via prompt box is received.
	// If there was running task in progress in session, it is interrupted and
	// user prompt is added to the conversation, then processing is resumed.
	UserPrompt(input string) error

	// Interrupt is called when user interrupts the current task.
	Interrupt() error
}

// SessionThreadOutput is an interface for handling output from the session.
type SessionThreadOutput interface {
	// ShowMessage shows a status message from session loop.
	ShowMessage(message string, messageType string)

	// AddUserMessage is called when a full user prompt message is queued for processing.
	AddUserMessage(text string)

	// AddAssistantMessage is called when a full assistant message is generated by LLM.
	AddAssistantMessage(text string, thinking string)

	// AddToolCall is called when assistant requests a tool call.
	AddToolCall(call *tool.ToolCall)

	// AddToolCallResult is called when tool call is completed and we have the final result.
	// This also includes errors if tool call failed, UI is responsible
	// for checking error status and displaying either result or error.
	AddToolCallResult(result *tool.ToolResponse)

	// RunFinished is called when the session Run() loop is finished.
	// This is called either when the session completes successfully (err == nil)
	// or when it encounters an error (err != nil).
	RunFinished(err error)

	// OnRateLimitError is called when the session encounters a rate limit error.
	// retryAfterSeconds is the estimated time in seconds when the request can be retried.
	// If retryAfterSeconds is 0, exponential backoff should be used.
	OnRateLimitError(retryAfterSeconds int)

	// ShouldRetryAfterFailure asks output handler whether exhausted transient failure should be retried.
	ShouldRetryAfterFailure(message string) bool
}

// SessionFactory creates a new session for a model and output handler.
type SessionFactory interface {
	NewSession(model string, outputHandler SessionThreadOutput) (*SweSession, error)
}

// SessionThread manages a session thread with input and context management.
// It ensures that SweSession is only called from a background thread and that
// at most one session loop is running at a time.
type SessionThread struct {
	system        SessionFactory
	outputHandler SessionThreadOutput

	mu                     sync.Mutex
	session                *SweSession
	sessionRunning         bool
	backgroundCtx          context.Context
	cancelFunc             context.CancelFunc
	inputQueue             []string
	interruptPending       bool
	paused                 bool
	suspended              bool
	resumePending          bool
}

// NewSessionThread creates a new SessionThread with the given system and output handler.
func NewSessionThread(system SessionFactory, outputHandler SessionThreadOutput) *SessionThread {
	return &SessionThread{
		system:        system,
		outputHandler: outputHandler,
		inputQueue:    make([]string, 0),
	}
}

// NewSessionThreadWithSession creates a new SessionThread with an existing session.
// This allows creating a new thread/presenter while preserving session state and messages.
func NewSessionThreadWithSession(system SessionFactory, session *SweSession, outputHandler SessionThreadOutput) *SessionThread {
	// Update the session's output handler to the new one
	if session != nil {
		session.outputHandler = outputHandler
	}
	return &SessionThread{
		system:        system,
		session:       session,
		outputHandler: outputHandler,
		inputQueue:    make([]string, 0),
	}
}

// GetSession returns the current session. Safe to call from any thread.
func (c *SessionThread) GetSession() *SweSession {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.session
}

// UserPrompt adds a user prompt to the session and starts processing if not already running.
// This method is non-blocking and thread-safe.
func (c *SessionThread) UserPrompt(input string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	// Initialize session if not already created
	if c.session == nil {
		return fmt.Errorf("SessionThread.UserPrompt() [session_thread.go]: session not initialized, call StartSession first")
	}

	if c.suspended {
		c.inputQueue = append(c.inputQueue, input)
		if !c.sessionRunning {
			c.suspended = false
			c.paused = false
			c.startSessionLocked()
		}
		return nil
	}

	// Add to input queue
	c.inputQueue = append(c.inputQueue, input)

	if c.session.logger != nil {
		c.session.logger.Debug("session_thread_user_prompt", "queue_length", len(c.inputQueue))
	}

	// If session is not running, start it
	if !c.sessionRunning {
		c.startSessionLocked()
	}

	return nil
}

// Interrupt cancels the current running session.
// This method is non-blocking and thread-safe.
func (c *SessionThread) Interrupt() error {
	c.mu.Lock()

	if c.suspended {
		c.suspended = false
		c.paused = false
		c.interruptPending = false
		outputHandler := c.outputHandler
		c.mu.Unlock()

		if outputHandler != nil {
			outputHandler.ShowMessage("Session terminated.", "info")
			outputHandler.RunFinished(fmt.Errorf("SessionThread.Interrupt() [session_thread.go]: terminated by interrupt while suspended"))
		}

		return nil
	}

	if !c.sessionRunning {
		c.mu.Unlock()
		return fmt.Errorf("SessionThread.Interrupt() [session_thread.go]: no session running to interrupt")
	}

	if c.session != nil && c.session.logger != nil {
		c.session.logger.Info("session_thread_interrupt")
	}

	removedPrompts := len(c.inputQueue)
	c.inputQueue = c.inputQueue[:0]
	c.interruptPending = false
	c.paused = true
	c.suspended = true
	cancelFunc := c.cancelFunc
	outputHandler := c.outputHandler
	c.mu.Unlock()

	if cancelFunc != nil {
		cancelFunc()
	}

	if outputHandler != nil {
		outputHandler.ShowMessage("Session suspended.", "info")
		if removedPrompts > 0 {
			outputHandler.ShowMessage(fmt.Sprintf("Removed %d queued user prompt(s).", removedPrompts), "warning")
		}
	}

	return nil
}

// AddPrompt adds a user prompt to the session without starting processing.
// This method is non-blocking and thread-safe.
// Use Resume() to start processing the queued prompts.
func (c *SessionThread) AddPrompt(input string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if c.session == nil {
		return fmt.Errorf("SessionThread.AddPrompt() [session_thread.go]: session not initialized, call StartSession first")
	}

	// Add to input queue
	c.inputQueue = append(c.inputQueue, input)

	return nil
}

// Pause stops the current session processing without signaling an error.
// The queue is preserved and can be resumed with Resume().
// This method is non-blocking and thread-safe.
func (c *SessionThread) Pause() error {
	c.mu.Lock()
	defer c.mu.Unlock()

	c.paused = true

	if c.sessionRunning && c.cancelFunc != nil {
		c.cancelFunc()
	}

	return nil
}

// Resume starts processing the queued prompts if not already running.
// This method is non-blocking and thread-safe.
func (c *SessionThread) Resume() error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if c.session == nil {
		return fmt.Errorf("SessionThread.Resume() [session_thread.go]: session not initialized, call StartSession first")
	}

	c.paused = false

	// Start processing if not already running and there are items in the queue
	if !c.sessionRunning && len(c.inputQueue) > 0 {
		c.startSessionLocked()
	}

	return nil
}

// ResumePending resumes the session processing without adding a new user prompt.
// It can be used to continue pending tool execution after restoring a session.
func (c *SessionThread) ResumePending() error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if c.session == nil {
		return fmt.Errorf("SessionThread.ResumePending() [session_thread.go]: session not initialized, call StartSession first")
	}

	c.paused = false
	c.resumePending = true

	if !c.sessionRunning {
		c.startSessionLocked()
	}

	return nil
}

// IsPaused returns true if the session is paused.
func (c *SessionThread) IsPaused() bool {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.paused
}

// IsRunning returns true if the session loop is currently running.
func (c *SessionThread) IsRunning() bool {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.sessionRunning
}

// SetOutputHandler sets the output handler for the controller.
// This method is thread-safe and can be called before or after StartSession.
// If called after StartSession, it will update the output handler for the existing session.
func (c *SessionThread) SetOutputHandler(handler SessionThreadOutput) {
	c.mu.Lock()
	defer c.mu.Unlock()

	c.outputHandler = handler
	if c.session != nil {
		c.session.outputHandler = handler
	}
}

// StartSession initializes a new session with the given model.
// This method is non-blocking and thread-safe.
func (c *SessionThread) StartSession(model string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if c.session != nil {
		return fmt.Errorf("SessionThread.StartSession() [session_thread.go]: session already exists")
	}

	if c.system == nil {
		return fmt.Errorf("SessionThread.StartSession() [session_thread.go]: session creator is nil")
	}

	session, err := c.system.NewSession(model, c.outputHandler)
	if err != nil {
		return err
	}

	c.session = session
	return nil
}

// startSessionLocked starts the background session loop.
// Must be called with c.mu held.
func (c *SessionThread) startSessionLocked() {
	if c.sessionRunning {
		return
	}

	c.sessionRunning = true
	c.backgroundCtx, c.cancelFunc = context.WithCancel(context.Background())

	go c.runSessionLoop()
}

// runSessionLoop is the background thread that processes the session.
func (c *SessionThread) runSessionLoop() {
	ctx := c.backgroundCtx

	defer func() {
		c.mu.Lock()
		c.sessionRunning = false
		c.backgroundCtx = nil
		c.cancelFunc = nil
		if c.suspended && len(c.inputQueue) > 0 {
			c.suspended = false
			c.paused = false
			c.startSessionLocked()
		}
		c.mu.Unlock()
	}()

	for {
		// Get next input from queue
		c.mu.Lock()
		if len(c.inputQueue) == 0 {
			if c.resumePending {
				c.resumePending = false
				c.interruptPending = false
				c.mu.Unlock()

				// Run the session without new input (processing pending state/tools)
				err := c.session.Run(ctx)
				if err != nil {
					c.outputHandler.RunFinished(err)
					return
				}

				// If successful, check if we need to continue loop (e.g. check queue again)
				c.mu.Lock()
				wasInterrupted := c.interruptPending
				wasPaused := c.paused
				wasSuspended := c.suspended
				c.mu.Unlock()

				if wasPaused {
					if !wasSuspended {
						c.outputHandler.RunFinished(nil)
					}
					return
				}
				if wasInterrupted {
					c.outputHandler.RunFinished(fmt.Errorf("SessionThread.runSessionLoop() [session_thread.go]: interrupted"))
					return
				}

				// Continue loop to check for more input
				continue
			}

			// No more input, stop the loop
			c.mu.Unlock()
			c.outputHandler.RunFinished(nil)
			return
		}

		// Check if paused
		if c.paused {
			c.mu.Unlock()
			c.outputHandler.RunFinished(nil)
			return
		}

		input := c.inputQueue[0]
		c.inputQueue = c.inputQueue[1:]
		c.interruptPending = false
		c.mu.Unlock()

		// Add user prompt to session (this is safe because we're in the background thread)
		if c.outputHandler != nil {
			c.outputHandler.AddUserMessage(input)
		}
		err := c.session.UserPrompt(input)
		if err != nil {
			c.outputHandler.RunFinished(err)
			return
		}

		// Run the session
		err = c.session.Run(ctx)

		// Check if we were interrupted or paused
		c.mu.Lock()
		wasInterrupted := c.interruptPending
		wasPaused := c.paused
		wasSuspended := c.suspended
		c.mu.Unlock()

		if wasPaused {
			if !wasSuspended {
				// Paused cleanly, no error
				c.outputHandler.RunFinished(nil)
			}
			return
		}

		if wasInterrupted {
			c.outputHandler.RunFinished(fmt.Errorf("SessionThread.runSessionLoop() [session_thread.go]: interrupted"))
			return
		}

		if err != nil {
			c.outputHandler.RunFinished(err)
			return
		}
	}
}
